language: node_js
node_js: node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Deploy
      node_js: node
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
